name: TEST

# on:
#   schedule:
#   - cron:  '*/15 * * * *'
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run
      run: touch hoge.text

    - name: TEST
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: test2
        title: 'test'
        branch: create-pull-request
