name: 'Java Setup'
description: 'Installs Java'

runs:
  using: 'composite'
  steps:
    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'gradle'
