name: Build Android project

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Java
      uses: ./.github/actions/setup-java
      id: java

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - uses: burrunan/gradle-cache-action@v1
      name: Build
      with:
        gradle-dependencies-cache-key: |
          gradle/libs.versions.toml
        arguments: build

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build-reports
        path: app/build/reports
