name: Build Android project

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Java
      uses: ./.github/actions/setup-java
      id: java

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - uses: burrunan/gradle-cache-action@v1
      name: Build
      with:
        gradle-dependencies-cache-key: |
          gradle/libs.versions.toml
        arguments: assemble

    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: app/build/outputs