name: TEST

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Run
      id: test
      run: touch hoge.text
    
    - name: test1
      if: ${{ steps.test.outputs.hoge != '' }}
      run: 
        echo "test1"

    - name: test2
      if: ${{ steps.test.outputs.hoge == '' }}
      run: 
        echo "test2"
