name: TEST

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Run
      run: touch hoge.text

    - name: TEST
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: format code by ktlint
        title: 'Run ktlint formatter'
        branch: format-code-by-ktlint
        labels: enhancement
